services:
  - type: web
    name: ai-image-generator-api
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: STABILITY_API_KEY
        sync: false
    autoDeploy: true 